//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoISO700.Models.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public int typeID { get; set; }
        public string company { get; set; }
        public string position { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public byte[] logo { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> DateExpires { get; set; }
        public int userId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual TypeJob TypeJob { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
